image: gitlab/dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: sources.meta-it.fr:4567/euskal-moneta/bdc:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: sources.meta-it.fr:4567/euskal-moneta/bdc

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN -e dev@meta-it.fr sources.meta-it.fr:4567

build_job:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE src/bdc
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - dind

test_job_develop:
  stage: test
  variables:
    ODOO_CONTAINER_TAG: dev
  script:
    #~ - docker network create --driver bridge eusko_net
    #~ - docker login -u $CI_SUPERUSER_USERNAME -p $CI_SUPERUSER_PASSWORD sources.meta-it.fr:4567
    - bash test.sh
  only:
    - develop
  tags:
    - dind

#~ test_job_staging:
  #~ stage: test
  #~ variables:
    #~ ODOO_CONTAINER_TAG: release
  #~ script:
    #~ - docker network create --driver bridge bb_net
    #~ # login as superuser to be able to pull images from other repositories
    #~ - docker login -u $CI_SUPERUSER_USERNAME -p $CI_SUPERUSER_PASSWORD sources.meta-it.fr:4567
#~ 
    #~ # start a postgres database container
    #~ - docker run --network=bb_net -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name bb_db postgres:9.5
#~ 
    #~ # start the odoo container
    #~ - docker run --network=bb_net -d --name bb_odoo -e DB_PORT_5432_TCP_ADDR=bb_db -e DB_PORT_5432_TCP_PORT=5432 -e DB_ENV_POSTGRES_USER=odoo -e DB_ENV_POSTGRES_PASSWORD=odoo sources.meta-it.fr:4567/bigarren-bizi/odoo:$ODOO_CONTAINER_TAG
#~ 
    #~ # create a fresh odoo database to perform tests
    #~ - docker run --network=bb_net --rm -e ODOO_DEMO=1 -e ODOO_ADMIN_PASSWORD=admin -e DATABASE_ADMIN_PASSWORD=odoo -e ODOO_PORT_8069_TCP_ADDR=bb_odoo -e ODOO_PORT_8069_TCP_PORT=8069 sources.meta-it.fr:4567/robin/create_odoo_db:latest bb bigarren_bizi
#~ 
    #~ # run tests
    #~ - docker run --rm --network=bb_net -e ODOO_PORT_8069_TCP_ADDR=bb_odoo -e ODOO_PORT_8069_TCP_PORT=8069 -e ODOO_DATABASE=bb $CONTAINER_TEST_IMAGE python manage.py test
  #~ only:
    #~ - /^release-.*$/
  #~ tags:
    #~ - dind
#~ 
#~ test_job:
  #~ stage: test
  #~ variables:
    #~ ODOO_CONTAINER_TAG: latest
  #~ script:
    #~ - docker network create --driver bridge bb_net
    #~ # login as superuser to be able to pull images from other repositories
    #~ - docker login -u $CI_SUPERUSER_USERNAME -p $CI_SUPERUSER_PASSWORD sources.meta-it.fr:4567
#~ 
    #~ # start a postgres database container
    #~ - docker run --network=bb_net -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name bb_db postgres:9.5
#~ 
    #~ # start the odoo container
    #~ - docker run --network=bb_net -d --name bb_odoo -e DB_PORT_5432_TCP_ADDR=bb_db -e DB_PORT_5432_TCP_PORT=5432 -e DB_ENV_POSTGRES_USER=odoo -e DB_ENV_POSTGRES_PASSWORD=odoo sources.meta-it.fr:4567/bigarren-bizi/odoo:$ODOO_CONTAINER_TAG
#~ 
    #~ # create a fresh odoo database to perform tests
    #~ - docker run --network=bb_net --rm -e ODOO_DEMO=1 -e ODOO_ADMIN_PASSWORD=admin -e DATABASE_ADMIN_PASSWORD=odoo -e ODOO_PORT_8069_TCP_ADDR=bb_odoo -e ODOO_PORT_8069_TCP_PORT=8069 sources.meta-it.fr:4567/robin/create_odoo_db:latest bb bigarren_bizi
#~ 
    #~ # run tests
    #~ - docker run --rm --network=bb_net -e ODOO_PORT_8069_TCP_ADDR=bb_odoo -e ODOO_PORT_8069_TCP_PORT=8069 -e ODOO_DATABASE=bb $CONTAINER_TEST_IMAGE python manage.py test
  #~ only:
    #~ - master
  #~ tags:
    #~ - dind

release_job:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE:latest
    - docker push $CONTAINER_RELEASE_IMAGE:latest
  only:
    - master
  tags:
    - dind

release_job_staging:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE:release
    - docker push $CONTAINER_RELEASE_IMAGE:release
  only:
    - /^release-.*$/
  tags:
    - dind

release_job_develop:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE:dev
    - docker push $CONTAINER_RELEASE_IMAGE:dev
  only:
    - develop
  tags:
    - dind

deploy_job_develop:
  stage: deploy
  script:
    - docker login -u $CI_SUPERUSER_USERNAME -p $CI_SUPERUSER_PASSWORD -e dev@meta-it.fr sources.meta-it.fr:4567
    - cd /home/meta-it/sources/eusko-dev
    - docker-compose pull bdc
    - docker-compose stop
    - docker-compose rm -f bdc
    - docker-compose up -d
  tags:
    - meta-it-f3
  only:
    - develop
  environment: dev