version: '2'

services:
  bureaudechange:
    build: src/bureaudechange
    volumes:
      - ./src/bureaudechange:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:8000
    links:
      - api
